# Docker Compose for running both apps
# File: docker-compose.yml

version: '3.8'

services:
  face-recognition:
    build: ./face-recognition-app
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    restart: unless-stopped
    
  nfc-contact:
    build: ./nfc-contact-app
    ports:
      - "5002:5002"
    environment:
      - ENV=production
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - face-recognition
      - nfc-contact
    restart: unless-stopped